Repository openshift/knative-client, pull requests merged in 2019-10, with the labels that each got.

#109 Adds RHEL based Dockerfile for client kn
  Dockerfile
  container.yaml
  content_sets.yaml
Labels: approved, lgtm, size/M

#123 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#125 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#119 Uses serverless operator to setup knative serving
  openshift/e2e-tests-openshift.sh
  openshift/olm/README.md
  openshift/olm/knative-serving.catalogsource.yaml
  openshift/serverless/operator-install.yaml
Labels: approved, lgtm, size/XL

#130 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#131 Parameterizes e2e timeout and parallel options values
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/S

#141 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#145 Remove unused scripts
  openshift/release/generate-release.sh
  openshift/release/resolve.sh
Labels: approved, lgtm, size/M
