Repository openshift/knative-client, pull requests merged in 2019-06, with the labels that each got.

#1 Adds OpenShift specific files
  LICENSE
  Makefile
  OWNERS
  OWNERS_ALIASES
  openshift/build-image/Dockerfile
  openshift/build-image/kubernetes.repo
  openshift/ci-operator/generate-ci-config.sh
  openshift/e2e-tests-openshift.sh
  openshift/release/README.md
  openshift/release/create-release-branch.sh
  openshift/release/generate-release.sh
  openshift/release/resolve.sh
  openshift/release/update-to-head.sh
Labels: lgtm, size/XL

#5 chore: Add missing license files
  Makefile
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/generate-ci-config.sh
  openshift/e2e-tests-openshift.sh
  openshift/release/create-release-branch.sh
  openshift/release/generate-release.sh
  openshift/release/resolve.sh
  openshift/release/update-to-head.sh
Labels: approved, size/L

#6 Adds missing license in yaml file
  openshift/olm/knative-serving.catalogsource.yaml
Labels: approved, lgtm, size/S
