Repository openshift/knative-client, pull requests merged in 2019-08, with the labels that each got.

#44 Updates serving release to v0.7.1
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#49 Fix: Updates source path to knative.dev for test-infra dependencies
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#45 Move catalogsource to the same namespace with subscription
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/S

#58 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#60 Runs e2e tests using go_test_e2e from test infra
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/S

#61 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#63 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#67 Adds Makefile target build-cross to build cross-platform binaries
  Makefile
  openshift/release/build-cross.sh
Labels: approved, size/M

#69 Uses hack/build.sh -x option to build cross platform for target in Makefile
  Makefile
  openshift/release/build-cross.sh
Labels: size/M

#71 Updates invoking e2e tests commands
  openshift/e2e-tests-openshift.sh
Labels: approved, size/XS

#72 Updates OLM namespace for OCP 4.2
  openshift/e2e-tests-openshift.sh
Labels: approved, size/S
