Repository openshift/knative-client, pull requests merged in 2019-12, with the labels that each got.

#194 Use hack/install.sh from serverless-operator repo
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#198 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#201 Eventing v0.10.0 setup
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/M

#204 :robot: CI was here...:fire:
  ci
Labels: approved, lgtm, size/XS

#205 Fix version for quay kn image
  Makefile
Labels: approved, lgtm, size/XS
