Repository openshift/knative-client, pull requests merged in 2020-03, with the labels that each got.

#285 Update Dockerfile at master branch
  Dockerfile
Labels: approved, lgtm, size/XS

#288 chore: Add CLI artifacts Dockerfile
  .gitignore
  Dockerfile.cliartifacts.rhel
  Dockerfile.rhel
  Makefile
  openshift/ci-operator/knative-images/client/Dockerfile.cliartifacts
  openshift/release/create-release-branch.sh
  openshift/release/update-to-head.sh
  package_cliartifacts.sh
Labels: approved, lgtm, size/L

#293 Grant all authenticated users access to anyuid SCC
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#294 Update Dockerfile.cliartifacts
  openshift/ci-operator/knative-images/client/Dockerfile.cliartifacts
Labels: approved, lgtm, size/S

#297 Removing myself from approver/reviewer
  OWNERS_ALIASES
Labels: size/XS

#299 Install python2 in cli-artifacts container for kn download server
  openshift/ci-operator/knative-images/client/Dockerfile.cliartifacts
Labels: approved, lgtm, size/XS

#307 Update RELEASE.md instructions for new kn-cli-artifacts image
  RELEASE.md
Labels: approved, lgtm

#308 Trigger CI
  ci
Labels: approved, lgtm

#309 Update version tag in Dockerfile
  Dockerfile.cliartifacts.rhel
  ci
Labels: approved, lgtm

#310 Update kn version tag to 0.13.1 in Dockerfiles
  Dockerfile.cliartifacts.rhel
  Dockerfile.rhel
Labels: approved, lgtm

#313 Add RPM SPEC file
  RELEASE.md
  openshift-serverless-clients.spec
Labels: approved, lgtm
