Repository openshift/knative-client, pull requests merged in 2020-02, with the labels that each got.

#257 :robot: Triggering CI on branch 'release-next' after synching to upstream/master
  ci
Labels: approved, kind/sync-fork-to-upstream, size/XS

#263 Update Dockerfile of build and test
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm, size/XS

#265 Unset GOFLAGS and explicitly set required go flags
  openshift/e2e-tests-openshift.sh
Labels: approved, size/XS

#271 Remove -parallel=1 flag from go test
  openshift/e2e-tests-openshift.sh
Labels: approved, lgtm, size/XS

#279 Update Dockerfile for release v0.12
  Dockerfile
Labels: approved, lgtm, size/XS
