Repository openshift/knative-client, pull requests merged in 2021-03, with the labels that each got.

#626 [release-v0.20.0] Update spec file
  openshift-serverless-clients.spec
Labels: approved, lgtm

#630 Make the scripts use main instead of master
  RELEASE.md
  openshift/ci-operator/generate-ci-config.sh
  openshift/release/create-release-branch.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#631 Pull in main from upstream
  openshift/release/README.md
  openshift/release/update-to-head.sh
Labels: approved, lgtm

#641 Pass revision to git-clone task for Tekton tests
  test/resources/tekton/kn-pipeline.yaml
Labels: approved, lgtm

#647 Fix arm64 download in serve.py
  serve.py
Labels: approved, lgtm

#652 fix: Remove deprecated image registry
  RELEASE.md
  openshift/ci-operator/build-image/Dockerfile
  openshift/e2e-common.sh
Labels: approved, lgtm

#653 fix: Fix golang image
  openshift/ci-operator/build-image/Dockerfile
Labels: approved, lgtm

#654 fix: Fix Eventing version in latest e2e tests
  openshift/e2e-common.sh
Labels: approved

#662 fix: Fix kubernetes repo gpg check
  openshift/ci-operator/build-image/kubernetes.repo
Labels: approved, lgtm

#657 [release-v0.19.1] Fix for serviceaccounts "default" not found flaky issue
  lib/test/integration.go
Labels: approved, lgtm, ok-to-test
