Repository openshift/knative-client, pull requests merged in 2022-09, with the labels that each got.

#1130 Update release step with plugins
  RELEASE.md
Labels: approved, lgtm

#1132 [release-v1.4] kn-workflow-plugin - update quarkus to downstream version
  hack/build.sh.d/kn-plugin-workflow.sh
Labels: needs-ok-to-test, approved, lgtm

#1135 Update latest spec file
  openshift-serverless-clients.spec
Labels: approved, lgtm

#1134 Add mirror-upstream-branches.sh script
  openshift/release/mirror-upstream-branches.sh
  openshift/release/update-to-head.sh
Labels: approved

#1138 Fix mirror script path
  openshift/release/mirror-upstream-branches.sh
Labels: approved
